[project]
name = "my-project"
version = "0.1.0"
description = "Lumerical Simulation framework"
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "pandas",
    "tqdm",
    "ipykernel",
    "seaborn",
    "scikit-learn",
    "salib",
    "gdstk",
    "pyDOE",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]